---
env:
  es6: true
  node: true
  mocha: true
extends: eslint:recommended
rules:
  no-console: 0
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
