provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"

service: s3-signature
functions:
  sign:
    handler: handler.sign
    warmup: true
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-plugin-warmup